### ISSUE TITLE
Change how the direction in ``alignY`` parameter called

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Zenitha#12]
Right now, we are using: ``up``, ``center``, ``down``
However, when talking about aligning an object vertically, native speakers will never use them, instead they use the words: ``top``, ``middle``, ``bottom``

Reference, from the screenshot of Microsoft Office PowerPoint 2021
![image](https://github.com/26F-Studio/Zenitha/assets/106439598/79e492b9-1ead-4447-b7d3-53cb293dfaa5)

**Comment by MrZ626** [comment]
editting

**Comment by SweetSea-ButImNotSweet** [comment]
Fixed in https://github.com/26F-Studio/Zenitha/commit/b6e6e225be68f1e99afcf834251702957076a37d
