### ISSUE TITLE
Some widgets have... weird alignment

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Zenitha#13]
For buttons:

| | Left | Center| Right|
|--------|--------|--------|--------|
| Top | ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/37d5a2e4-6d70-48f0-8159-8b0c7a5843ed)| ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/24667065-1f12-4b8b-8114-92c604c93fdf)| ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/1ebe0150-02bd-4216-bd3d-d9937a3e013c)|
| Middle | ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/79fd6ace-45b2-41d8-8a27-ec0e2291392b) | ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/e7c029fb-3aaa-4046-b669-2ae199f837b1) | ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/925f48c8-11d4-45dc-8c80-9fa48f67e339) |
| Bottom | ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/8907bc42-e269-4298-998e-dc014a4c667f)| ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/bb2ff61a-b133-4a71-9516-c1c87ec948d7)| ![image](https://github.com/26F-Studio/Zenitha/assets/106439598/99d02b96-35a0-481f-a776-a97028d04ba3)|

My expected behavior:
![image](https://github.com/26F-Studio/Zenitha/assets/106439598/d39cd4bb-319e-47c7-b9bd-4f780aaf05c0)

For some other widgets, it uses the default alignX and alignY, although it should be "left" and "top" respectively

**Comment by MrZ626** [comment]
notice that `top-left` will move text's `top-left` corner to the center of the button
but you are right, I'll try to make it support more positions including yours
